"""Game tag registry -- maps every game key to game-theoretic property tags."""

from __future__ import annotations

from constant_definitions.batch4.tag_constants import (
    # Communication
    NO_COMMUNICATION, CHEAP_TALK, COSTLY_SIGNALING,
    BINDING_COMMITMENT, MEDIATED,
    # Information
    COMPLETE_INFORMATION, INCOMPLETE_INFORMATION, ASYMMETRIC_INFORMATION,
    # Structure
    SIMULTANEOUS, SEQUENTIAL, REPEATED, SINGLE_SHOT,
    # Payoff type
    ZERO_SUM, SYMMETRIC_PAYOFF, ASYMMETRIC_PAYOFF,
    COORDINATION, ANTI_COORDINATION,
    # Domain
    SOCIAL_DILEMMA, AUCTION, BARGAINING, VOTING,
    MARKET_COMPETITION, EVOLUTIONARY, SECURITY, NETWORK,
    # Action space
    BINARY_CHOICE, SMALL_CHOICE, LARGE_CHOICE,
    # Multiplayer dimensions
    MULTIPLAYER, COALITION_FORMATION,
    PENALTY_ENFORCEMENT, BINDING_ENFORCEMENT, META_GOVERNANCE,
    # Category grouping
    CATEGORIES,
)

# ---------------------------------------------------------------------------
# Game-to-tag mapping (one line per game, alphabetical within modules)
# ---------------------------------------------------------------------------

GAME_TAGS: dict[str, frozenset[str]] = {
    # ── Base games (server/games.py) ──
    "prisoners_dilemma": frozenset({NO_COMMUNICATION, COMPLETE_INFORMATION, SIMULTANEOUS, REPEATED, SYMMETRIC_PAYOFF, SOCIAL_DILEMMA, BINARY_CHOICE}),
    "stag_hunt": frozenset({NO_COMMUNICATION, COMPLETE_INFORMATION, SIMULTANEOUS, REPEATED, COORDINATION, SOCIAL_DILEMMA, BINARY_CHOICE}),
    "hawk_dove": frozenset({NO_COMMUNICATION, COMPLETE_INFORMATION, SIMULTANEOUS, REPEATED, ANTI_COORDINATION, SOCIAL_DILEMMA, BINARY_CHOICE}),
    "ultimatum": frozenset({NO_COMMUNICATION, COMPLETE_INFORMATION, SEQUENTIAL, SINGLE_SHOT, ASYMMETRIC_PAYOFF, BARGAINING, LARGE_CHOICE}),
    "trust": frozenset({NO_COMMUNICATION, COMPLETE_INFORMATION, SEQUENTIAL, SINGLE_SHOT, ASYMMETRIC_PAYOFF, SOCIAL_DILEMMA, LARGE_CHOICE}),
    "public_goods": frozenset({NO_COMMUNICATION, COMPLETE_INFORMATION, SIMULTANEOUS, SINGLE_SHOT, SYMMETRIC_PAYOFF, SOCIAL_DILEMMA, LARGE_CHOICE}),

    # ── games_ext/matrix_games.py ──
    "matching_pennies": frozenset({NO_COMMUNICATION, COMPLETE_INFORMATION, SIMULTANEOUS, REPEATED, ZERO_SUM, SECURITY, BINARY_CHOICE}),
    "rock_paper_scissors": frozenset({NO_COMMUNICATION, COMPLETE_INFORMATION, SIMULTANEOUS, REPEATED, ZERO_SUM, SECURITY, SMALL_CHOICE}),
    "battle_of_the_sexes": frozenset({NO_COMMUNICATION, COMPLETE_INFORMATION, SIMULTANEOUS, REPEATED, COORDINATION, BARGAINING, BINARY_CHOICE}),
    "pure_coordination": frozenset({NO_COMMUNICATION, COMPLETE_INFORMATION, SIMULTANEOUS, REPEATED, COORDINATION, SOCIAL_DILEMMA, BINARY_CHOICE}),
    "deadlock": frozenset({NO_COMMUNICATION, COMPLETE_INFORMATION, SIMULTANEOUS, REPEATED, SYMMETRIC_PAYOFF, SOCIAL_DILEMMA, BINARY_CHOICE}),
    "harmony": frozenset({NO_COMMUNICATION, COMPLETE_INFORMATION, SIMULTANEOUS, REPEATED, SYMMETRIC_PAYOFF, SOCIAL_DILEMMA, BINARY_CHOICE}),

    # ── games_ext/sequential.py ──
    "dictator": frozenset({NO_COMMUNICATION, COMPLETE_INFORMATION, SEQUENTIAL, SINGLE_SHOT, ASYMMETRIC_PAYOFF, BARGAINING, LARGE_CHOICE}),
    "centipede": frozenset({NO_COMMUNICATION, COMPLETE_INFORMATION, SEQUENTIAL, SINGLE_SHOT, SYMMETRIC_PAYOFF, SOCIAL_DILEMMA, BINARY_CHOICE}),
    "stackelberg": frozenset({NO_COMMUNICATION, COMPLETE_INFORMATION, SEQUENTIAL, SINGLE_SHOT, ASYMMETRIC_PAYOFF, MARKET_COMPETITION, LARGE_CHOICE}),

    # ── games_ext/auction.py ──
    "first_price_auction": frozenset({NO_COMMUNICATION, INCOMPLETE_INFORMATION, SIMULTANEOUS, SINGLE_SHOT, ASYMMETRIC_PAYOFF, AUCTION, LARGE_CHOICE}),
    "vickrey_auction": frozenset({NO_COMMUNICATION, INCOMPLETE_INFORMATION, SIMULTANEOUS, SINGLE_SHOT, ASYMMETRIC_PAYOFF, AUCTION, LARGE_CHOICE}),
    "allpay_auction": frozenset({NO_COMMUNICATION, INCOMPLETE_INFORMATION, SIMULTANEOUS, SINGLE_SHOT, ASYMMETRIC_PAYOFF, AUCTION, LARGE_CHOICE}),

    # ── games_ext/nplayer.py ──
    "tragedy_of_commons": frozenset({NO_COMMUNICATION, COMPLETE_INFORMATION, SIMULTANEOUS, SINGLE_SHOT, SYMMETRIC_PAYOFF, SOCIAL_DILEMMA, LARGE_CHOICE}),
    "volunteer_dilemma": frozenset({NO_COMMUNICATION, COMPLETE_INFORMATION, SIMULTANEOUS, SINGLE_SHOT, SYMMETRIC_PAYOFF, SOCIAL_DILEMMA, BINARY_CHOICE}),
    "el_farol": frozenset({NO_COMMUNICATION, INCOMPLETE_INFORMATION, SIMULTANEOUS, REPEATED, ANTI_COORDINATION, SOCIAL_DILEMMA, BINARY_CHOICE}),

    # ── games_ext/generated.py ──
    "random_symmetric_3x3": frozenset({NO_COMMUNICATION, COMPLETE_INFORMATION, SIMULTANEOUS, REPEATED, SYMMETRIC_PAYOFF, SOCIAL_DILEMMA, SMALL_CHOICE}),
    "random_asymmetric_3x3": frozenset({NO_COMMUNICATION, COMPLETE_INFORMATION, SIMULTANEOUS, REPEATED, ASYMMETRIC_PAYOFF, SOCIAL_DILEMMA, SMALL_CHOICE}),

    # ── games_info/signaling.py ──
    "beer_quiche": frozenset({COSTLY_SIGNALING, INCOMPLETE_INFORMATION, SEQUENTIAL, SINGLE_SHOT, ASYMMETRIC_PAYOFF, SECURITY, BINARY_CHOICE}),
    "spence_signaling": frozenset({COSTLY_SIGNALING, ASYMMETRIC_INFORMATION, SEQUENTIAL, SINGLE_SHOT, ASYMMETRIC_PAYOFF, MARKET_COMPETITION, LARGE_CHOICE}),
    "cheap_talk": frozenset({CHEAP_TALK, INCOMPLETE_INFORMATION, SEQUENTIAL, SINGLE_SHOT, COORDINATION, SOCIAL_DILEMMA, SMALL_CHOICE}),
    "lemon_market": frozenset({NO_COMMUNICATION, ASYMMETRIC_INFORMATION, SIMULTANEOUS, SINGLE_SHOT, ASYMMETRIC_PAYOFF, MARKET_COMPETITION, LARGE_CHOICE}),
    "bayesian_persuasion": frozenset({CHEAP_TALK, ASYMMETRIC_INFORMATION, SEQUENTIAL, SINGLE_SHOT, ASYMMETRIC_PAYOFF, BARGAINING, BINARY_CHOICE}),

    # ── games_info/contracts.py ──
    "moral_hazard": frozenset({BINDING_COMMITMENT, ASYMMETRIC_INFORMATION, SEQUENTIAL, SINGLE_SHOT, ASYMMETRIC_PAYOFF, MARKET_COMPETITION, SMALL_CHOICE}),
    "screening": frozenset({NO_COMMUNICATION, ASYMMETRIC_INFORMATION, SEQUENTIAL, SINGLE_SHOT, ASYMMETRIC_PAYOFF, MARKET_COMPETITION, SMALL_CHOICE}),
    "gift_exchange": frozenset({NO_COMMUNICATION, COMPLETE_INFORMATION, SEQUENTIAL, SINGLE_SHOT, ASYMMETRIC_PAYOFF, SOCIAL_DILEMMA, LARGE_CHOICE}),

    # ── games_info/communication.py ──
    "cheap_talk_pd": frozenset({CHEAP_TALK, COMPLETE_INFORMATION, SIMULTANEOUS, REPEATED, SYMMETRIC_PAYOFF, SOCIAL_DILEMMA, SMALL_CHOICE}),
    "binding_commitment": frozenset({BINDING_COMMITMENT, COMPLETE_INFORMATION, SEQUENTIAL, SINGLE_SHOT, SYMMETRIC_PAYOFF, SOCIAL_DILEMMA, SMALL_CHOICE}),
    "correlated_equilibrium": frozenset({MEDIATED, COMPLETE_INFORMATION, SIMULTANEOUS, SINGLE_SHOT, SYMMETRIC_PAYOFF, SOCIAL_DILEMMA, BINARY_CHOICE}),
    "focal_point": frozenset({NO_COMMUNICATION, COMPLETE_INFORMATION, SIMULTANEOUS, SINGLE_SHOT, COORDINATION, SOCIAL_DILEMMA, SMALL_CHOICE}),
    "mediated_game": frozenset({MEDIATED, COMPLETE_INFORMATION, SIMULTANEOUS, SINGLE_SHOT, SYMMETRIC_PAYOFF, SOCIAL_DILEMMA, BINARY_CHOICE}),

    # ── games_info/bayesian.py ──
    "global_game": frozenset({NO_COMMUNICATION, INCOMPLETE_INFORMATION, SIMULTANEOUS, SINGLE_SHOT, COORDINATION, SOCIAL_DILEMMA, BINARY_CHOICE}),
    "jury_voting": frozenset({NO_COMMUNICATION, INCOMPLETE_INFORMATION, SIMULTANEOUS, SINGLE_SHOT, SYMMETRIC_PAYOFF, VOTING, BINARY_CHOICE}),
    "information_cascade": frozenset({NO_COMMUNICATION, INCOMPLETE_INFORMATION, SEQUENTIAL, SINGLE_SHOT, SYMMETRIC_PAYOFF, NETWORK, BINARY_CHOICE}),
    "adverse_selection_insurance": frozenset({NO_COMMUNICATION, ASYMMETRIC_INFORMATION, SIMULTANEOUS, SINGLE_SHOT, ASYMMETRIC_PAYOFF, MARKET_COMPETITION, SMALL_CHOICE}),

    # ── games_info/network.py ──
    "security_game": frozenset({NO_COMMUNICATION, INCOMPLETE_INFORMATION, SIMULTANEOUS, REPEATED, ZERO_SUM, SECURITY, SMALL_CHOICE}),
    "link_formation": frozenset({NO_COMMUNICATION, COMPLETE_INFORMATION, SIMULTANEOUS, SINGLE_SHOT, SYMMETRIC_PAYOFF, NETWORK, BINARY_CHOICE}),
    "trust_with_punishment": frozenset({NO_COMMUNICATION, COMPLETE_INFORMATION, SEQUENTIAL, SINGLE_SHOT, ASYMMETRIC_PAYOFF, SOCIAL_DILEMMA, LARGE_CHOICE}),
    "dueling_game": frozenset({NO_COMMUNICATION, COMPLETE_INFORMATION, SEQUENTIAL, SINGLE_SHOT, ZERO_SUM, SECURITY, SMALL_CHOICE}),

    # ── games_market/oligopoly.py ──
    "cournot": frozenset({NO_COMMUNICATION, COMPLETE_INFORMATION, SIMULTANEOUS, SINGLE_SHOT, SYMMETRIC_PAYOFF, MARKET_COMPETITION, LARGE_CHOICE}),
    "bertrand": frozenset({NO_COMMUNICATION, COMPLETE_INFORMATION, SIMULTANEOUS, SINGLE_SHOT, SYMMETRIC_PAYOFF, MARKET_COMPETITION, LARGE_CHOICE}),
    "hotelling": frozenset({NO_COMMUNICATION, COMPLETE_INFORMATION, SIMULTANEOUS, SINGLE_SHOT, SYMMETRIC_PAYOFF, MARKET_COMPETITION, LARGE_CHOICE}),
    "entry_deterrence": frozenset({NO_COMMUNICATION, COMPLETE_INFORMATION, SEQUENTIAL, SINGLE_SHOT, ASYMMETRIC_PAYOFF, MARKET_COMPETITION, BINARY_CHOICE}),
    "nash_demand": frozenset({NO_COMMUNICATION, COMPLETE_INFORMATION, SIMULTANEOUS, SINGLE_SHOT, SYMMETRIC_PAYOFF, BARGAINING, LARGE_CHOICE}),
    "double_auction": frozenset({NO_COMMUNICATION, INCOMPLETE_INFORMATION, SIMULTANEOUS, SINGLE_SHOT, ASYMMETRIC_PAYOFF, AUCTION, LARGE_CHOICE}),

    # ── games_market/contests.py ──
    "colonel_blotto": frozenset({NO_COMMUNICATION, COMPLETE_INFORMATION, SIMULTANEOUS, SINGLE_SHOT, ZERO_SUM, SECURITY, SMALL_CHOICE}),
    "war_of_attrition": frozenset({NO_COMMUNICATION, COMPLETE_INFORMATION, SIMULTANEOUS, SINGLE_SHOT, SYMMETRIC_PAYOFF, BARGAINING, LARGE_CHOICE}),
    "tullock_contest": frozenset({NO_COMMUNICATION, COMPLETE_INFORMATION, SIMULTANEOUS, SINGLE_SHOT, SYMMETRIC_PAYOFF, MARKET_COMPETITION, LARGE_CHOICE}),
    "inspection_game": frozenset({NO_COMMUNICATION, COMPLETE_INFORMATION, SIMULTANEOUS, REPEATED, ZERO_SUM, SECURITY, BINARY_CHOICE}),
    "rubinstein_bargaining": frozenset({NO_COMMUNICATION, COMPLETE_INFORMATION, SEQUENTIAL, SINGLE_SHOT, SYMMETRIC_PAYOFF, BARGAINING, LARGE_CHOICE}),
    "divide_and_choose": frozenset({NO_COMMUNICATION, COMPLETE_INFORMATION, SEQUENTIAL, SINGLE_SHOT, SYMMETRIC_PAYOFF, BARGAINING, LARGE_CHOICE}),

    # ── games_market/classic.py ──
    "travelers_dilemma": frozenset({NO_COMMUNICATION, COMPLETE_INFORMATION, SIMULTANEOUS, SINGLE_SHOT, SYMMETRIC_PAYOFF, SOCIAL_DILEMMA, LARGE_CHOICE}),
    "dollar_auction": frozenset({NO_COMMUNICATION, COMPLETE_INFORMATION, SEQUENTIAL, SINGLE_SHOT, ASYMMETRIC_PAYOFF, AUCTION, LARGE_CHOICE}),
    "unscrupulous_diner": frozenset({NO_COMMUNICATION, COMPLETE_INFORMATION, SIMULTANEOUS, SINGLE_SHOT, SYMMETRIC_PAYOFF, SOCIAL_DILEMMA, LARGE_CHOICE}),
    "minority_game": frozenset({NO_COMMUNICATION, COMPLETE_INFORMATION, SIMULTANEOUS, REPEATED, ANTI_COORDINATION, SOCIAL_DILEMMA, BINARY_CHOICE}),
    "rpsls": frozenset({NO_COMMUNICATION, COMPLETE_INFORMATION, SIMULTANEOUS, REPEATED, ZERO_SUM, SECURITY, SMALL_CHOICE}),

    # ── games_market/advanced.py ──
    "preemption_game": frozenset({NO_COMMUNICATION, COMPLETE_INFORMATION, SIMULTANEOUS, SINGLE_SHOT, ASYMMETRIC_PAYOFF, MARKET_COMPETITION, SMALL_CHOICE}),
    "war_of_gifts": frozenset({NO_COMMUNICATION, COMPLETE_INFORMATION, SIMULTANEOUS, SINGLE_SHOT, SYMMETRIC_PAYOFF, SOCIAL_DILEMMA, SMALL_CHOICE}),
    "penalty_shootout": frozenset({NO_COMMUNICATION, COMPLETE_INFORMATION, SIMULTANEOUS, REPEATED, ZERO_SUM, SECURITY, SMALL_CHOICE}),

    # ── games_market/generated_v2.py ──
    "random_zero_sum_3x3": frozenset({NO_COMMUNICATION, COMPLETE_INFORMATION, SIMULTANEOUS, REPEATED, ZERO_SUM, SECURITY, SMALL_CHOICE}),
    "random_coordination_3x3": frozenset({NO_COMMUNICATION, COMPLETE_INFORMATION, SIMULTANEOUS, REPEATED, COORDINATION, SOCIAL_DILEMMA, SMALL_CHOICE}),
    "parameterized_chicken": frozenset({NO_COMMUNICATION, COMPLETE_INFORMATION, SIMULTANEOUS, REPEATED, ANTI_COORDINATION, SOCIAL_DILEMMA, BINARY_CHOICE}),

    # ── games_coop/cooperative.py ──
    "shapley_allocation": frozenset({BINDING_COMMITMENT, COMPLETE_INFORMATION, SIMULTANEOUS, SINGLE_SHOT, SYMMETRIC_PAYOFF, BARGAINING, LARGE_CHOICE}),
    "core_divide_dollar": frozenset({BINDING_COMMITMENT, COMPLETE_INFORMATION, SIMULTANEOUS, SINGLE_SHOT, SYMMETRIC_PAYOFF, BARGAINING, LARGE_CHOICE}),
    "weighted_voting": frozenset({NO_COMMUNICATION, COMPLETE_INFORMATION, SIMULTANEOUS, SINGLE_SHOT, SYMMETRIC_PAYOFF, VOTING, BINARY_CHOICE}),
    "stable_matching": frozenset({NO_COMMUNICATION, COMPLETE_INFORMATION, SIMULTANEOUS, SINGLE_SHOT, ASYMMETRIC_PAYOFF, NETWORK, SMALL_CHOICE}),
    "median_voter": frozenset({NO_COMMUNICATION, COMPLETE_INFORMATION, SIMULTANEOUS, SINGLE_SHOT, SYMMETRIC_PAYOFF, VOTING, LARGE_CHOICE}),
    "approval_voting": frozenset({NO_COMMUNICATION, COMPLETE_INFORMATION, SIMULTANEOUS, SINGLE_SHOT, SYMMETRIC_PAYOFF, VOTING, SMALL_CHOICE}),

    # ── games_coop/pd_variants.py ──
    "optional_pd": frozenset({NO_COMMUNICATION, COMPLETE_INFORMATION, SIMULTANEOUS, REPEATED, SYMMETRIC_PAYOFF, SOCIAL_DILEMMA, SMALL_CHOICE}),
    "asymmetric_pd": frozenset({NO_COMMUNICATION, COMPLETE_INFORMATION, SIMULTANEOUS, REPEATED, ASYMMETRIC_PAYOFF, SOCIAL_DILEMMA, BINARY_CHOICE}),
    "donation_game": frozenset({NO_COMMUNICATION, COMPLETE_INFORMATION, SIMULTANEOUS, REPEATED, SYMMETRIC_PAYOFF, SOCIAL_DILEMMA, BINARY_CHOICE}),
    "friend_or_foe": frozenset({NO_COMMUNICATION, COMPLETE_INFORMATION, SIMULTANEOUS, REPEATED, SYMMETRIC_PAYOFF, SOCIAL_DILEMMA, BINARY_CHOICE}),
    "peace_war": frozenset({NO_COMMUNICATION, COMPLETE_INFORMATION, SIMULTANEOUS, REPEATED, SYMMETRIC_PAYOFF, SOCIAL_DILEMMA, BINARY_CHOICE}),

    # ── games_coop/dynamic.py ──
    "bank_run": frozenset({NO_COMMUNICATION, INCOMPLETE_INFORMATION, SIMULTANEOUS, SINGLE_SHOT, COORDINATION, SOCIAL_DILEMMA, BINARY_CHOICE}),
    "global_stag_hunt": frozenset({NO_COMMUNICATION, INCOMPLETE_INFORMATION, SIMULTANEOUS, SINGLE_SHOT, COORDINATION, SOCIAL_DILEMMA, BINARY_CHOICE}),
    "beauty_contest": frozenset({NO_COMMUNICATION, COMPLETE_INFORMATION, SIMULTANEOUS, SINGLE_SHOT, SYMMETRIC_PAYOFF, MARKET_COMPETITION, LARGE_CHOICE}),
    "hawk_dove_bourgeois": frozenset({NO_COMMUNICATION, COMPLETE_INFORMATION, SIMULTANEOUS, REPEATED, ANTI_COORDINATION, EVOLUTIONARY, SMALL_CHOICE}),
    "finitely_repeated_pd": frozenset({NO_COMMUNICATION, COMPLETE_INFORMATION, SIMULTANEOUS, REPEATED, SYMMETRIC_PAYOFF, SOCIAL_DILEMMA, BINARY_CHOICE}),
    "markov_game": frozenset({NO_COMMUNICATION, COMPLETE_INFORMATION, SIMULTANEOUS, REPEATED, SYMMETRIC_PAYOFF, SOCIAL_DILEMMA, BINARY_CHOICE}),

    # ── games_coop/infinite.py ──
    "continuous_pd": frozenset({NO_COMMUNICATION, COMPLETE_INFORMATION, SIMULTANEOUS, REPEATED, SYMMETRIC_PAYOFF, SOCIAL_DILEMMA, LARGE_CHOICE}),
    "discounted_pd": frozenset({NO_COMMUNICATION, COMPLETE_INFORMATION, SIMULTANEOUS, REPEATED, SYMMETRIC_PAYOFF, SOCIAL_DILEMMA, BINARY_CHOICE}),

    # ── games_coop/stochastic.py ──
    "stochastic_pd": frozenset({NO_COMMUNICATION, INCOMPLETE_INFORMATION, SIMULTANEOUS, REPEATED, SYMMETRIC_PAYOFF, SOCIAL_DILEMMA, BINARY_CHOICE}),
    "risk_dominance": frozenset({NO_COMMUNICATION, COMPLETE_INFORMATION, SIMULTANEOUS, SINGLE_SHOT, COORDINATION, EVOLUTIONARY, BINARY_CHOICE}),
    "threshold_public_goods": frozenset({NO_COMMUNICATION, COMPLETE_INFORMATION, SIMULTANEOUS, SINGLE_SHOT, SYMMETRIC_PAYOFF, SOCIAL_DILEMMA, LARGE_CHOICE}),
    "evolutionary_pd": frozenset({NO_COMMUNICATION, COMPLETE_INFORMATION, SIMULTANEOUS, REPEATED, SYMMETRIC_PAYOFF, EVOLUTIONARY, BINARY_CHOICE}),

    # ── N-player games (common/games_meta/nplayer_games.py) ──
    "nplayer_public_goods": frozenset({NO_COMMUNICATION, COMPLETE_INFORMATION, SIMULTANEOUS, REPEATED, SYMMETRIC_PAYOFF, SOCIAL_DILEMMA, LARGE_CHOICE, MULTIPLAYER}),
    "nplayer_volunteer_dilemma": frozenset({NO_COMMUNICATION, COMPLETE_INFORMATION, SIMULTANEOUS, REPEATED, SYMMETRIC_PAYOFF, SOCIAL_DILEMMA, BINARY_CHOICE, MULTIPLAYER}),
    "nplayer_el_farol": frozenset({NO_COMMUNICATION, INCOMPLETE_INFORMATION, SIMULTANEOUS, REPEATED, ANTI_COORDINATION, SOCIAL_DILEMMA, BINARY_CHOICE, MULTIPLAYER}),

    # ── Coalition games (common/games_meta/coalition_config.py) ──
    "coalition_cartel": frozenset({CHEAP_TALK, COMPLETE_INFORMATION, SIMULTANEOUS, REPEATED, SYMMETRIC_PAYOFF, MARKET_COMPETITION, BINARY_CHOICE, MULTIPLAYER, COALITION_FORMATION, PENALTY_ENFORCEMENT, META_GOVERNANCE}),
    "coalition_alliance": frozenset({CHEAP_TALK, COMPLETE_INFORMATION, SIMULTANEOUS, REPEATED, SYMMETRIC_PAYOFF, SOCIAL_DILEMMA, BINARY_CHOICE, MULTIPLAYER, COALITION_FORMATION, META_GOVERNANCE}),
    "coalition_voting": frozenset({BINDING_COMMITMENT, COMPLETE_INFORMATION, SIMULTANEOUS, REPEATED, SYMMETRIC_PAYOFF, VOTING, BINARY_CHOICE, MULTIPLAYER, COALITION_FORMATION, BINDING_ENFORCEMENT, META_GOVERNANCE}),
    "coalition_ostracism": frozenset({CHEAP_TALK, COMPLETE_INFORMATION, SIMULTANEOUS, REPEATED, ASYMMETRIC_PAYOFF, SOCIAL_DILEMMA, SMALL_CHOICE, MULTIPLAYER, COALITION_FORMATION, PENALTY_ENFORCEMENT, META_GOVERNANCE}),
    "coalition_resource_trading": frozenset({CHEAP_TALK, COMPLETE_INFORMATION, SIMULTANEOUS, REPEATED, SYMMETRIC_PAYOFF, MARKET_COMPETITION, BINARY_CHOICE, MULTIPLAYER, COALITION_FORMATION, META_GOVERNANCE}),
    "coalition_rule_voting": frozenset({BINDING_COMMITMENT, COMPLETE_INFORMATION, SIMULTANEOUS, REPEATED, SYMMETRIC_PAYOFF, VOTING, BINARY_CHOICE, MULTIPLAYER, COALITION_FORMATION, BINDING_ENFORCEMENT, META_GOVERNANCE}),
    "coalition_commons": frozenset({CHEAP_TALK, COMPLETE_INFORMATION, SIMULTANEOUS, REPEATED, SYMMETRIC_PAYOFF, SOCIAL_DILEMMA, BINARY_CHOICE, MULTIPLAYER, COALITION_FORMATION, PENALTY_ENFORCEMENT, META_GOVERNANCE}),

    # ── meta/meta_games.py ──
    "rule_proposal_prisoners_dilemma": frozenset({BINDING_COMMITMENT, COMPLETE_INFORMATION, SIMULTANEOUS, REPEATED, SYMMETRIC_PAYOFF, SOCIAL_DILEMMA, LARGE_CHOICE, META_GOVERNANCE}),
    "rule_proposal_stag_hunt": frozenset({BINDING_COMMITMENT, COMPLETE_INFORMATION, SIMULTANEOUS, REPEATED, COORDINATION, SOCIAL_DILEMMA, LARGE_CHOICE, META_GOVERNANCE}),
    "rule_proposal_hawk_dove": frozenset({BINDING_COMMITMENT, COMPLETE_INFORMATION, SIMULTANEOUS, REPEATED, ANTI_COORDINATION, SOCIAL_DILEMMA, LARGE_CHOICE, META_GOVERNANCE}),
    "rule_signal_prisoners_dilemma": frozenset({CHEAP_TALK, COMPLETE_INFORMATION, SIMULTANEOUS, REPEATED, SYMMETRIC_PAYOFF, SOCIAL_DILEMMA, LARGE_CHOICE, META_GOVERNANCE}),
    "rule_signal_stag_hunt": frozenset({CHEAP_TALK, COMPLETE_INFORMATION, SIMULTANEOUS, REPEATED, COORDINATION, SOCIAL_DILEMMA, LARGE_CHOICE, META_GOVERNANCE}),
    "rule_signal_hawk_dove": frozenset({CHEAP_TALK, COMPLETE_INFORMATION, SIMULTANEOUS, REPEATED, ANTI_COORDINATION, SOCIAL_DILEMMA, LARGE_CHOICE, META_GOVERNANCE}),

    # ── games_adaptive/factories.py ──
    "adaptive_prisoners_dilemma": frozenset({NO_COMMUNICATION, COMPLETE_INFORMATION, SIMULTANEOUS, REPEATED, SYMMETRIC_PAYOFF, SOCIAL_DILEMMA, BINARY_CHOICE}),
    "arms_race": frozenset({NO_COMMUNICATION, COMPLETE_INFORMATION, SIMULTANEOUS, REPEATED, ANTI_COORDINATION, SOCIAL_DILEMMA, BINARY_CHOICE}),
    "trust_erosion": frozenset({NO_COMMUNICATION, COMPLETE_INFORMATION, SIMULTANEOUS, REPEATED, SYMMETRIC_PAYOFF, SOCIAL_DILEMMA, BINARY_CHOICE}),
    "market_dynamics": frozenset({NO_COMMUNICATION, COMPLETE_INFORMATION, SIMULTANEOUS, REPEATED, SYMMETRIC_PAYOFF, MARKET_COMPETITION, SMALL_CHOICE}),
    "reputation_payoffs": frozenset({NO_COMMUNICATION, COMPLETE_INFORMATION, SIMULTANEOUS, REPEATED, SYMMETRIC_PAYOFF, SOCIAL_DILEMMA, BINARY_CHOICE}),

    # ── meta/meta_games.py (gossip) ──
    "gossip_prisoners_dilemma": frozenset({CHEAP_TALK, COMPLETE_INFORMATION, SIMULTANEOUS, REPEATED, SYMMETRIC_PAYOFF, SOCIAL_DILEMMA, LARGE_CHOICE, META_GOVERNANCE}),
    "gossip_stag_hunt": frozenset({CHEAP_TALK, COMPLETE_INFORMATION, SIMULTANEOUS, REPEATED, COORDINATION, SOCIAL_DILEMMA, LARGE_CHOICE, META_GOVERNANCE}),
    "gossip_hawk_dove": frozenset({CHEAP_TALK, COMPLETE_INFORMATION, SIMULTANEOUS, REPEATED, ANTI_COORDINATION, SOCIAL_DILEMMA, LARGE_CHOICE, META_GOVERNANCE}),
}


# ---------------------------------------------------------------------------
# Query helpers
# ---------------------------------------------------------------------------


def derive_variant_tags(
    base_tags: frozenset[str], variant_name: str,
) -> frozenset[str]:
    """Compute tags for a composed variant game from base game tags."""
    tags = set(base_tags)
    if variant_name == "cheap_talk":
        tags.discard(NO_COMMUNICATION)
        tags.add(CHEAP_TALK)
        tags.discard(BINARY_CHOICE)
        tags.add(SMALL_CHOICE)
    elif variant_name == "binding_commitment":
        tags.discard(NO_COMMUNICATION)
        tags.add(BINDING_COMMITMENT)
        tags.discard(BINARY_CHOICE)
        tags.add(SMALL_CHOICE)
    elif variant_name == "exit":
        tags.discard(BINARY_CHOICE)
        tags.add(SMALL_CHOICE)
    elif variant_name == "gossip":
        tags.discard(NO_COMMUNICATION)
        tags.add(CHEAP_TALK)
        tags.discard(BINARY_CHOICE)
        tags.add(LARGE_CHOICE)
        tags.add(META_GOVERNANCE)
    return frozenset(tags)


def get_games_by_tag(tag: str) -> list[str]:
    """Return all game keys that have the given tag."""
    return [key for key, tags in GAME_TAGS.items() if tag in tags]


def get_games_by_tags(*tags: str) -> list[str]:
    """Return game keys that have *all* of the specified tags."""
    tag_set = frozenset(tags)
    return [key for key, gtags in GAME_TAGS.items() if tag_set <= gtags]


def list_tags() -> list[str]:
    """Return every unique tag across all games, sorted."""
    all_tags: set[str] = set()
    for tags in GAME_TAGS.values():
        all_tags |= tags
    return sorted(all_tags)


def list_categories() -> dict[str, list[str]]:
    """Return tag constants grouped by dimension name."""
    return dict(CATEGORIES)
