"""Weight constants for the arena reputation scoring system."""

# Signal weights (numerator / denominator)
COOPERATION_WEIGHT_NUMERATOR = 3
COOPERATION_WEIGHT_DENOMINATOR = 10

HONESTY_WEIGHT_NUMERATOR = 3
HONESTY_WEIGHT_DENOMINATOR = 10

FAIRNESS_WEIGHT_NUMERATOR = 2
FAIRNESS_WEIGHT_DENOMINATOR = 10

PEER_RATING_WEIGHT_NUMERATOR = 2
PEER_RATING_WEIGHT_DENOMINATOR = 10

# Default reputation score
DEFAULT_ARENA_SCORE_NUMERATOR = 5
DEFAULT_ARENA_SCORE_DENOMINATOR = 10

# Voting weight floor
VOTING_WEIGHT_FLOOR_NUMERATOR = 1
VOTING_WEIGHT_FLOOR_DENOMINATOR = 10

# Decay rate for EMA updates
ARENA_DECAY_NUMERATOR = 9
ARENA_DECAY_DENOMINATOR = 10
