"""Constants for adaptive payoff games."""

# Adaptive PD: cooperation multiplier range
ADAPTIVE_PD_MULTIPLIER_MIN_NUMERATOR = 5
ADAPTIVE_PD_MULTIPLIER_MIN_DENOMINATOR = 10

ADAPTIVE_PD_MULTIPLIER_MAX_NUMERATOR = 2
ADAPTIVE_PD_MULTIPLIER_MAX_DENOMINATOR = 1

ADAPTIVE_PD_MULTIPLIER_STEP_NUMERATOR = 1
ADAPTIVE_PD_MULTIPLIER_STEP_DENOMINATOR = 10

# Arms Race: cost escalation per round
ARMS_RACE_COST_STEP_NUMERATOR = 1
ARMS_RACE_COST_STEP_DENOMINATOR = 2

ARMS_RACE_MAX_COST_NUMERATOR = 5
ARMS_RACE_MAX_COST_DENOMINATOR = 1

# Trust Erosion: multiplier decay after defection
TRUST_EROSION_DECAY_NUMERATOR = 8
TRUST_EROSION_DECAY_DENOMINATOR = 10

TRUST_EROSION_RECOVERY_NUMERATOR = 1
TRUST_EROSION_RECOVERY_DENOMINATOR = 10

# Market dynamics: demand shift per round
MARKET_DEMAND_SHIFT_NUMERATOR = 1
MARKET_DEMAND_SHIFT_DENOMINATOR = 2

# Reputation payoffs: cooperation bonus scaling
REPUTATION_BONUS_NUMERATOR = 1
REPUTATION_BONUS_DENOMINATOR = 5

# Default rounds for adaptive games
ADAPTIVE_DEFAULT_ROUNDS = 10

# Game type identifier
ADAPTIVE_GAME_TYPE = "adaptive"
