# --- Coalition phase parameters ---
COALITION_PHASE_NEGOTIATE = "negotiate"
COALITION_PHASE_ACTION = "action"

# --- Enforcement modes ---
ENFORCEMENT_CHEAP_TALK = "cheap_talk"
ENFORCEMENT_PENALTY = "penalty"
ENFORCEMENT_BINDING = "binding"

# --- Default penalty fraction (penalty = payoff * NUM / DEN) ---
COALITION_DEFAULT_PENALTY_NUMERATOR = 1
COALITION_DEFAULT_PENALTY_DENOMINATOR = 2

# --- Default side payment ---
COALITION_DEFAULT_SIDE_PAYMENT = 0

# --- Default rounds for coalition games ---
COALITION_DEFAULT_ROUNDS = 10

# --- Cartel Game (penalty enforcement) ---
CARTEL_NUM_PLAYERS = 4
CARTEL_COLLUDE_THRESHOLD = 3
CARTEL_COLLUDE_HIGH = 6
CARTEL_COLLUDE_LOW = 2
CARTEL_COMPETE_HIGH = 10
CARTEL_COMPETE_LOW = 4

# --- Alliance Formation (cheap talk) ---
ALLIANCE_NUM_PLAYERS = 4
ALLIANCE_SUPPORT_POOL = 20
ALLIANCE_BETRAY_GAIN = 8
ALLIANCE_NO_SUPPORT = 2

# --- Coalition Voting (binding) ---
VOTING_NUM_PLAYERS = 5
VOTING_WINNER_PAYOFF = 6
VOTING_LOSER_PAYOFF = 2

# --- Ostracism (penalty) ---
OSTRACISM_NUM_PLAYERS = 5
OSTRACISM_BONUS_POOL = 20
OSTRACISM_EXCLUDED_PAYOFF = 0
OSTRACISM_BASE_PAYOFF = 3
OSTRACISM_MAJORITY_NUMERATOR = 1
OSTRACISM_MAJORITY_DENOMINATOR = 2

# --- Resource Trading (cheap talk) ---
TRADE_NUM_PLAYERS = 4
TRADE_DIVERSE_PAYOFF = 6
TRADE_HOMOGENEOUS_PAYOFF = 2
TRADE_MINORITY_BONUS = 2

# --- Rule Voting (binding) ---
RULE_NUM_PLAYERS = 4
RULE_EQUAL_PAY = 5
RULE_WINNER_HIGH = 8
RULE_WINNER_LOW = 2

# --- Commons Governance (penalty) ---
COMMONS_NUM_PLAYERS = 5
COMMONS_SUSTAINABLE_THRESHOLD = 2
COMMONS_LOW_SUSTAINABLE = 4
COMMONS_HIGH_SUSTAINABLE = 7
COMMONS_LOW_DEPLETED = 1
COMMONS_HIGH_DEPLETED = 2
