# --- Governance proposal types ---
GOVERNANCE_PROPOSAL_PARAMETER = "parameter"
GOVERNANCE_PROPOSAL_MECHANIC = "mechanic"
GOVERNANCE_PROPOSAL_CUSTOM = "custom"

# --- Mechanic names (applied in this fixed order) ---
MECHANIC_TAXATION = "taxation"
MECHANIC_REDISTRIBUTION = "redistribution"
MECHANIC_INSURANCE = "insurance"
MECHANIC_QUOTA = "quota"
MECHANIC_SUBSIDY = "subsidy"
MECHANIC_VETO = "veto"

MECHANIC_ORDER = [
    MECHANIC_TAXATION,
    MECHANIC_REDISTRIBUTION,
    MECHANIC_INSURANCE,
    MECHANIC_QUOTA,
    MECHANIC_SUBSIDY,
    MECHANIC_VETO,
]

# --- Redistribution modes ---
REDISTRIBUTION_EQUAL = "equal"
REDISTRIBUTION_PROPORTIONAL = "proportional"

# --- Voting thresholds ---
GOVERNANCE_MAJORITY_NUMERATOR = 1
GOVERNANCE_MAJORITY_DENOMINATOR = 2

# --- Per-round limits ---
GOVERNANCE_MAX_PROPOSALS_PER_ROUND = 3

# --- Default mechanic parameters ---
GOVERNANCE_DEFAULT_TAX_RATE_NUMERATOR = 1
GOVERNANCE_DEFAULT_TAX_RATE_DENOMINATOR = 10

GOVERNANCE_DEFAULT_REDISTRIBUTION_MODE = REDISTRIBUTION_EQUAL
GOVERNANCE_DEFAULT_REDISTRIBUTION_DAMPING_NUMERATOR = 1
GOVERNANCE_DEFAULT_REDISTRIBUTION_DAMPING_DENOMINATOR = 2

GOVERNANCE_DEFAULT_INSURANCE_CONTRIBUTION_NUMERATOR = 1
GOVERNANCE_DEFAULT_INSURANCE_CONTRIBUTION_DENOMINATOR = 10
GOVERNANCE_DEFAULT_INSURANCE_THRESHOLD_NUMERATOR = 1
GOVERNANCE_DEFAULT_INSURANCE_THRESHOLD_DENOMINATOR = 2

GOVERNANCE_DEFAULT_QUOTA_MAX = 8

GOVERNANCE_DEFAULT_SUBSIDY_FLOOR = 2
GOVERNANCE_DEFAULT_SUBSIDY_FUND_RATE_NUMERATOR = 1
GOVERNANCE_DEFAULT_SUBSIDY_FUND_RATE_DENOMINATOR = 5

GOVERNANCE_DEFAULT_VETO_PLAYER = 0

# --- Custom modifier safety ---
GOVERNANCE_CUSTOM_DELTA_CLAMP_NUMERATOR = 1
GOVERNANCE_CUSTOM_DELTA_CLAMP_DENOMINATOR = 2
