# --- N-player environment parameters ---
MIN_PLAYERS = 2
MAX_PLAYERS = 10
NPLAYER_DEFAULT_ROUNDS = 10

# --- Public Goods (N-player) ---
NPG_ENDOWMENT = 20
NPG_MULTIPLIER_NUMERATOR = 3
NPG_MULTIPLIER_DENOMINATOR = 2

# --- Volunteer's Dilemma (N-player) ---
NVD_BENEFIT = 6
NVD_COST = 2
NVD_NO_VOLUNTEER = 0

# --- El Farol Bar (N-player) ---
NEF_CAPACITY_FRACTION_NUMERATOR = 3
NEF_CAPACITY_FRACTION_DENOMINATOR = 5
NEF_ATTEND_REWARD = 4
NEF_CROWD_PENALTY = -1
NEF_STAY_HOME = 2
